#!/bin/bash -eu
# Copyright 2015 the Massachusetts Institute of Technology
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License.  You may obtain a copy of
# the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
# License for the specific language governing permissions and limitations under
# the License.

if [[ 1 < $# ]]; then
    echo "usage: $0 [fresh]" >&2
    exit 1
fi

urweb -dbms sqlite -db "dbname=urwiki.sqlite3" -sql initialize.sql -output urwiki urwiki

if [[ $# == 1 && $1 == "fresh" ]]; then
    rm urwiki.sqlite3
    sqlite3 urwiki.sqlite3 <initialize.sql
fi
